apiVersion: v1
kind: ConfigMap
metadata:
  name: shadowtraffic-config
  namespace: datagen
data:
  v0_local_gen_minio.json: |
    {
      "generators": 
      [
        {
          "connection": "s3",
          "bucket": "landing",
          "data": {
            "_gen": "oneOf",
            "choices": ["👍", "🔥", "❤️"]
          },
          "bucketConfigs": {
            "format": "jsonl",
            "keyPrefix": "part-"
          }
        }
      ],
      "connections": {
        "s3": {
          "kind": "s3",
          "connectionConfigs": {
            "endpoint": "http://minio.deepstorage.svc.cluster.local:9000",
            "pathStyleAccess": true,
            "forcePathStyle": true 
          }
        }
      }
    }