services:
  shadowtraffic:
    image: shadowtraffic/shadowtraffic:latest
    container_name: shadowtraffic-minio-connector
    volumes:
      - ./v0_local_gen_minio.json:/workspace/v0_local_gen_minio.json
    env_file:
      - ./license.env
    environment:
      - AWS_ACCESS_KEY_ID=miniouser
      - AWS_SECRET_ACCESS_KEY=miniosecret
    entrypoint: ["java", "-Djava.security.manager=allow", "-jar", "/home/shadowtraffic.jar"]
    command: ["--config", "/workspace/v0_local_gen_minio.json"]