services:
  shadowtraffic:
    image: shadowtraffic/shadowtraffic:latest
    container_name: shadowtraffic-minio-connector
    volumes:
      - ./v0_local_gen_minio.json:/workspace/v0_local_gen_minio.json
    env_file:
      - ./license.env
    entrypoint: ["java", "-Daws.region=us-east-1", "-Djava.security.manager=allow", "-jar", "/home/shadowtraffic.jar"]
    command: ["--config", "/workspace/v0_local_gen_minio.json"]